### ISSUE TITLE
Typescript Migration

### ISSUE THREAD

**Issue by nirmalhk7** [IET-NITK/IET-NITK.github.io#165]
- [ ] Migrate `.js` to `.tsx`.
- [ ] Upgrade the ESLint plugins accordingly.

**Comment by NimperX** [comment]
Hi @nirmalhk7 May i work on thus issue?

**Comment by nirmalhk7** [comment]
Hey Nimna, please do. 
But make sure that you define all the types as they are, and not just use `any` (because that defeats the point of type checking :sweat_smile:)
