### ISSUE TITLE
Image allignment issue

### ISSUE THREAD

**Issue by nirmalhk7** [IET-NITK/IET-NITK.github.io#193]
Fix image allignment issue as attached below.
I think this issue happens on all article pages (events and blogs)

![Screenshot from 2021-11-03 21-19-58](https://user-images.githubusercontent.com/25480443/140095314-3024f864-bb3d-44d9-b950-1d9367ff5de8.png)

**Comment by MBSA-INFINITY** [comment]
Working on it
