### ISSUE TITLE
Upgrade bootstrap   

### ISSUE THREAD

**Issue by gaurav-chaurasia** [IET-NITK/IET-NITK.github.io#81]
- [ ] change all the bootstrap 4 classes to bootstrap 5 
- [ ] tags are not looking same as earlier 
- [ ] header goes transparent on scroll

**Comment by nirmalhk7** [comment]
For now I've turned Bootstrap 5 back to 4, because we have blogs coming up very quickly, but anyone who's taking this issue can upgrade it back to 5 and fix the navbar and tags as Gaurav mentioned above.
