### ISSUE TITLE
ChatBot

### ISSUE THREAD

**Issue by iamindhu** [IET-NITK/IET-NITK.github.io#86]
Add new feature ChatBot

**Comment by nirmalhk7** [comment]
@iamindhu is it working? This would be an interesting addition to our website, let me know if you need help

**Comment by iamindhu** [comment]
> @iamindhu is it working? This would be an interesting addition to our website, let me know if you need help

Yes, it answers all the basic queries that I can think of

**Comment by nirmalhk7** [comment]
Okay, you can push an MR for it.

**Comment by nirmalhk7** [comment]
Closing this for now. Interesting idea, but until we're on GitHub Pages (basically a static host) this wont be possible.
